#!/usr/bin/env bash
# set -e
# cat ./.next-version-arg >/dev/null 2>&1 || {
# 	echo 'Run "./version <type>" where <type> is either major, minor, or patch.'
# 	exit 1
# }
# echo "Version:" "$(cat ./.next-version-arg)"
# $(npm bin)/gulp
# git add -f lib-* production.js
# git commit -m 'prepublish build'
# npm version "$(cat ./.next-version-arg)"
# git push
# git push --tags
